[project]
name = "pyseed"
version = "0.1.0"
dependencies = [

]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest"
]

[tool.ruff]
line-length = 88
target-version = "py312"
lint.select = ["E", "F", "I", "N", "UP", "B"]
lint.ignore = ["E501"]
